{-# LANGUAGE TemplateHaskell #-}

{-|

This module contains the parsed rules from the upstream publicsuffix list. The
rules are autogenerated using Template-Haskell.

You should not need this module directly, all interesting functions are exposed
in the 'Data.PublicSuffix' module. It is only exposed so that we can run tests
on the actual rules list instead of having to mock the data. The list is not
that long, so running exhaustive tests on the full list is feasible.

-}

module Data.PublicSuffix.Rules where

import Data.PublicSuffix.Types
import Data.PublicSuffix.TH


-- rules :: [Rule]
mkRules "rules" ($(moduleDirectory) ++ "public_suffix_list.dat")
